### ISSUE TITLE
This app is great, but needs more features

### ISSUE THREAD

**Issue by eric2788** [dokeraj/AndroTainer#20]
Just found this amazing app that can remote control my containers via an android app. However currently it can just list all containers and their status, start or stop the containers. Would you plan to make more features in future ?
I hope it would have
- container logger
- add an container
- pull an image
etc

**Comment by dokeraj** [comment]
@eric2788 
I'm glad that you find the app useful. For now, I'm only planning to add logging, since I find myself oftentimes wanting to review the log of a container.

As for the adding of a container, there are a lot of inputs that are required to spin up a new container, so doing it from a mobile device is more cumbersome than doing the same thing on a desktop machine.

Could you elaborate on why would you need just to pull an image?

Regards

**Comment by eric2788** [comment]
Well actually just wanna see if it can do the same feature like from desktop portainer. 
The most necessary feature that I mostly would like to have is checking logs and stats(ram cpu usages)

**Comment by dokeraj** [comment]
@eric2788 I've started working on the logging, but I cannot promise how long it will take until it is live, since I'm working on it on and off.

**Comment by eric2788** [comment]
okay, I already watched this repository and waiting for the release, good luck!
