### ISSUE TITLE
Do you have any plan to support the multiple portainer endpoint?

### ISSUE THREAD

**Issue by Zhao-Michael** [dokeraj/AndroTainer#23]
https://github.com/dokeraj/AndroTainer/blob/53c739dd3f7aea186ba621b5f7dda08e76c4373a/app/src/main/res/values/strings.xml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L20

Currently, the endpoint of portainer was hard-coded to 1 in the reference line.

I can't login in with AndroTainer now, since the endpoints of my portainer happen to be 2 and 3. 😂

**Comment by dokeraj** [comment]
Hi Michael,

Androtainer only supports just the first endpoint as you've noticed :). I
initially imagined that users will go with the defaults of portainer
settings, so that is why I hardcoded the endpoint (I personally have just
one endpoint).

For now I don't plan to extend to this functionality, but if there is
increasing interest for this, I might be swayed into making the changes, so
it can be an user input.

Regards,
Zarko

**Comment by dokeraj** [comment]
Hi Michael,

I've found out the issue - in the latest version of portainer, they made
some breaking changes (with the endpoints), so I will need to make the
corresponding changes to Portainer.

Also can you send me the response (it's a jsArray) of the API: *GET
http://yourPortainerIP.com/api/endpoints?limit=100&start=0*
I only have the endpoint number two (2). I'm just mostly interested to see
what value you have in the jsString *name.*

Sorry for the inconvenience.

Regards,
Zarko

**Comment by dokeraj** [comment]
This is weird.

What version of MIUI are you using? Can you check to see if the problem is
also present in the details view (single click on a container name)? You
can crosscheck with the screenshots in play store.

I will check to see if this is the case for all MIUI os-es.

As for the support for multiple  endpoints, I'm not planning to support it
for now.

**Comment by Zhao-Michael** [comment]
MIUI 12.5.4  Android 11.

And the details view looks good.

**Comment by Zhao-Michael** [comment]
Great, Thanks a lot 👍
