### ISSUE TITLE
CertPathValidatorException on self signed certificate over HTTPS

### ISSUE THREAD

**Issue by progtologist** [dokeraj/AndroTainer#38]
Hello and thanks for the great tool!
Androtainer worked without any issues until a few weeks ago (I think, I did not notice exactly when it stopped working).
I am running portainer behind a reverse proxy with HTTPS on a self signed certificate.

When trying to connect over the FQDN, I am getting a "Server not permitting communication! ava.security.cert.CertPathValidatorException: Trus..." error.
My guess is that android does not like self-signed certs (similarly to how it doesn't like non-google DNS).
Is there any chance this can be worked around without exposing the raw http API?

**Comment by dokeraj** [comment]
Hi,
In fact I have setup portainer through reverse proxy (nginx) and I access it through `https://myDomain/portainer`. I use the docker image from linuxserver.io - `swag` which has letsencrypt certificate. Everything works fine.

I suggest when you run portainer you use the following docker run command `docker run -d -p 9000:9000 --name portainer --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest`. Only use the port `9000` which is http (since when you access it locally you don't need https). 

If you want help with setting up SWAG I can help.

**Comment by progtologist** [comment]
I guess the main difference with your setup is that your certificate (and domain) are publicly validated while mine are not.
It is not in my immediate plans to purchase a domain for home usage, so far my PiHole intercepts all local DNS queries and if they resolve internally (*.lan) they will never leave to reach the WAN.

Similarly, I do not care about letsencrypt signing the certificates because I do not actually own the domain, it is a local domain that I have my own certificates for. I have those certificates accepted into my machines and I don't have any problems with that in normal operating systems, but android does not (AFAIK) provide any mechanism to accept or import certificates so there is not much that I can do about it.

**Comment by dokeraj** [comment]
If I'm understanding you correctly you access portainer only while you're on your local network correct? If that is the case you can still use Androtainer by using the local IP address of the machine where portainer is deployed `http://yourLocalip:9000`.

Also what version of android do you have on your device?

**Comment by progtologist** [comment]
You are correct, everything is either accessed when in the LAN or through VPN.
Port 9000 of portainer is not exposed at all, everything escapes the docker private network through a reverse proxy container (with authorization when needed). 
I know that I can export port 9000 (or even reverse proxy without SSL), but I would prefer to maintain https even when on LAN, as I could have users that might want to "test" their IT/hacking skills on the network. My setup is somewhat SOHO, some security is deployed, but nothing enterprise level.

I am running Android 11.

**Comment by dokeraj** [comment]
I understand. There is very little I can do, since android somehow doesn't
allow self signed certificates.
And as to why it worked and suddenly stopped, I have no clue. I haven't
made any changes that would affect the certification on the this project.

Sorry I cannot be of more help.

**Comment by progtologist** [comment]
No worries, thanks for the effort!

**Comment by kesawi** [comment]
Other apps I've used with self signed certificates have a configuration option that allows the user to choose to accept unsigned certificates.

Looking at https://developer.android.com/training/articles/security-ssl it appears you can configure your app to trust self-signed certificates and custom CAs.

Potentially you could use the configuration settings at https://developer.android.com/training/articles/security-config#LimitingCas. If it's possible you could create a checkbox on the login screen that gets the app to read the domain name/IP and also extract the custom CA certificate, it could then assign these parameters to the configuration and allow the connection. Clearing the checkbox would return to normal function.

It would be great if this would work as I access my portainer instance externally.

**Comment by dokeraj** [comment]
Hi,

I believe that this is an edge case, since most commonly users have a
reverse proxy setup, that has certificates that the android app by default
is recognizing.
I can suggest that you use linuxserver.io's SWAG container to generate
letsencrypt certificate and then setup nginx, so you can securely connect
to portainer from outside your LAN. This is tested and this is the way that
I initially made the app to work.

Sorry, for the inconvenience.

**Comment by kesawi** [comment]
Unfortunately I'm stuck with GoDaddy for my domain which doesn't support Let's Encrypt Certificates.

Regardless, sending data in the clear even over an internal network isn't really best practice as @progtologist highlighted and ins't really a good workaround.

I'd argue it's not an edge issue but a relatively common situation where users either don't want to or can't set up Let's Encrypt, or would prefer not to use plain HTTP internally.

**Comment by dokeraj** [comment]
@kesawi one can also argue that if you let an unauthorized third party into your private LAN, then you have far bigger issues than, whether your internal connection to portainer is HTTP or HTTPS.

But, we are not here to argue, but to find solutions. 
I also have my domain registered with GoDaddy and haven't got any issue with using Let's Encrypt Certificates (as stated before - they were created by `swag` image). The only thing that I've modified is that I've changed the DNS nameservers in GoDaddy to point to `dynu.com`'s nameservers. You can see it from the following image:
![godaddynameservers](https://user-images.githubusercontent.com/76596154/149588240-a9d93f65-baae-436d-8965-de10acc4a355.png)

**Comment by kesawi** [comment]
@dokeraj thanks for your assitance with a solution, and developing and maintinaing the app. I agree with you that we leave it as agreeing to disagree :)

In terms of a solution for my situation, the downside with GoDaddy is their API gives too much power and it doesn't appear possible to restrict what a given API key can do. I'd therefore prefer to not to expose API access to my main domain. Unfortunately I need to stick with them for various resons. I've setup a Freenom domain with Dynu to allow ACME to work in DNS alias mode so that I don't have my main domain exposed to API access. I've tested this and it works on my pfSense firewall, but need to set it up on my docker host. There appears to be limited docker packages that support both ACME DNS alias and Dynu API, however, I think I've found a solution but have other priorities at the moment.
