### ISSUE TITLE
Login error with SSL

### ISSUE THREAD

**Issue by gabriel-lando** [dokeraj/AndroTainer#39]
Hi, since I moved Portainer to HTTPS, I can't login anymore in the app.
I'm using Let's Encrypt to generate the SSL certificate and it's working well when I access with the browser, but I can't login on the app.

This is the error I have when I try to login:
![Screenshot_20220107-184506_AndroTainer](https://user-images.githubusercontent.com/18423120/148644343-7c3f96fd-3fdb-4b25-bf26-ecb113e02a2e.jpg)

The SSL certificate is valid and working, as we can see:
![Screenshot_20220107-184547_Samsung Internet](https://user-images.githubusercontent.com/18423120/148644363-46f6f9e1-e5b7-44aa-b2e5-a7cfdf1eee78.jpg)

Thanks :)

**Comment by dokeraj** [comment]
@gabriel-lando I'm guessing that you're accessing your portainer instance only from inside your LAN? If so, there is no need to access it using https, you should instead use port `9000` and use http. 

Android for some reason doesn't support self-signed certificates when using `https` on a local IP address. 

I'm using linuxserver.io's `swag` docker image for creating a certificate and when I access Portainer from outside of my LAN using `https://myDomain.com`, I have no such issues. When I try to login

**Comment by gabriel-lando** [comment]
@dokeraj Hi, hmmm it's weird.
I'm also using swag to generate the certificate.
I disabled the port 9000 and I'm using only the 9443 to HTTPS.
But I can't access even outside my LAN (using a mobile connection or my brother's WiFi).

For local access, I'll reenable the 9000, but I'm still facing issues with the https outside :(

**Comment by dokeraj** [comment]
@gabriel-lando you need to use the certificate from swag and use nginx reverse proxy to connect to port 9000. So you actually don't ever need to access portainer through their `https`. You let nginx take care of forcing the connection to be `https`.

I can help you with the nginx config file for portainer if you'd like.

**Comment by gabriel-lando** [comment]
@dokeraj hmmm I didn't know that. I never user nginx before. If it's not asking too much, could you provide me the nginx config file? Thanks :)

**Comment by dokeraj** [comment]
Ok, as you said, your ISP is blocking 80 and 443, so you can use ports 450 to be mapped to 443 and port 90 to be mapped to 80. I assume that you are familiar with port forwarding, so in your router you will need to set the port forwarding rules:

Rule 1:
- External Port: 450
- Internal Port: 450
- IP: local machine IP that hosts your docker server (where swag and portainer are located)

Rule 2:
- External Port: 90
- Internal Port: 90
- IP: local machine IP that hosts your docker server (where swag and portainer are located)

This way you will bypass the restrictions your ISP has set. The next thing you need to do is setup SWAG so it will listen to external port 450 and 90 and then remap itself to port 443 and 80 respectfully (inside the container it will be remapped to these two).

But before you create a swag container you need to create a docker bridge network. This is so the containers can communicate with each other by their container name, instead of their IP addresses (it makes life a lot easier, especially if you are going to recreate some of these containers)

Here are the docker run commands:
`docker network create -d bridge <NAME_OF_YOUR_NETWORK>` (you can swap <NAME_OF_YOUR_NETWORK> with whatever name you'd like) 

`docker run -d --name=swag --cap-add=NET_ADMIN --network=<NAME_OF_YOUR_NETWORK> -e PUID=1000 -e PGID=1000 -e URL=<YOUR_DOMAIN> -e SUBDOMAINS=portainer,<ANY_OTHER_SERVICE_YOU_HAVE> -e VALIDATION=http -e EMAIL=<YOUR_EMAIL> -e STAGING=false -p 450:443 -p 90:80 -v <PATH_TO_SWAG_CONFIG>:/config --restart unless-stopped ghcr.io/linuxserver/swag:latest`

Note that all the _<TAG>_ values need to be swapped with your data. As you can see in the `- p` values we are remapping the port 450 to 443 and port 90 to 80, so SWAG internally will still use port 443 and 80. Also make sure that the env var `SUBDOMAINS` have the `portainer` subdomain, since that is the same name we will use in the NGINX config file. Also I already assume that in your domain provider, you've allowed `portainer` subdomain to be allowed to be used.

After you've run swag, you will need to create the portainer container:
`docker run -d -p 9000:9000 --name portainer --net=<NAME_OF_YOUR_NETWORK> --restart unless-stopped -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest`

Make sure that the name of the docker container is called `portainer`, since that is what we will use in the NGINX config file.

Now you should browse to the following folder (where you've bind the <PATH_TO_SWAG_CONFIG>). For example I've set it up in `mySharedFolders/myApplicationData/swag` once you're in that folder you should find the following subfolder `nginx/proxy-confs` so the whole path in my case would be `mySharedFolders/myApplicationData/swag/nginx/proxy-confs`. 
There you will find a file called `portainer.subdomain.conf.sample`.  All you need to do is just rename the file to be called `portainer.subdomain.conf` (without the .sample).

The last step is restart swag container and monitor the logs it displays. If all goes well, you can then access portainer using the following url `https://portainer.yourDomain.com:450`

If you have any additional questions just ask :)

**Comment by gabriel-lando** [comment]
Hi @dokeraj , thanks a lot :) I was doing a very hard job, I didn't know it was so easy to do.

I was using swag to generate the certificate and sharing the same volume with portainer to ger the certificate and configuring the SSL inside the portainer.

Following your previous message, I could successfully access my server using your app outside my LAN via HTTPS. Also, I can connect inside my LAN using the same HTTPS connection :)

Also, just one important observation in case someone else tries to do this: as my ISP blocks ports 80 and 443 and Let's Encrypt uses port 80 to validate the domain using HTTP (VALIDATION=http), I had to change the validation to DNS, because the protocol used to validate the domain uses obligatorily the port 80 as mentioned in the swag documentation.

**Comment by gabriel-lando** [comment]
I'll close this issue, thanks a lot for your help :) Also, your app is awesome, you did a great job.
